# Heartbeat workflow definitions
# Checkpoint 1: Heartbeat Workflow DSL
# Defines scheduled jobs, retry/backoff policies, and failure alert hooks via `message` tool

version: 1

jobs:
  nightly_review:
    description: "Nightly Evolution Cron Job"
    schedule: "0 2 * * *"
    command: "scripts/nightly_review.py --dry-run"
    retry:
      max_attempts: 3
      backoff:
        initial_delay: "5m"
        factor: 2
    on_failure:
      - message:
          channel: telegram
          target: "+14123348429"
          message: "Job nightly_review failed after {{attempts}} attempts."

  rotate_memory:
    description: "Daily Memory rotation"
    schedule: "0 0 * * *"
    command: "scripts/rotate_memory.py"
    retry:
      max_attempts: 3
      backoff:
        initial_delay: "5m"
        factor: 2
    on_failure:
      - message:
          channel: telegram
          target: "+14123348429"
          message: "Job rotate_memory failed after {{attempts}} attempts."

  heartbeat_summary_morning:
    description: "Morning summary at 9:00"
    schedule: "0 9 * * *"
    command: "scripts/heartbeat_summary.py"
    retry:
      max_attempts: 3
      backoff:
        initial_delay: "5m"
        factor: 2
    on_failure:
      - message:
          channel: telegram
          target: "+14123348429"
          message: "Job heartbeat_summary_morning failed after {{attempts}} attempts."

  heartbeat_summary_evening:
    description: "Evening summary at 18:00"
    schedule: "0 18 * * *"
    command: "scripts/heartbeat_summary.py"
    retry:
      max_attempts: 3
      backoff:
        initial_delay: "5m"
        factor: 2
    on_failure:
      - message:
          channel: telegram
          target: "+14123348429"
          message: "Job heartbeat_summary_evening failed after {{attempts}} attempts."

  system_pulse:
    description: "System Pulse (5min keep-alive)"
    schedule: "*/5 * * * *"
    command: "echo 'pulse'"
    retry:
      max_attempts: 1
      backoff:
        initial_delay: "1m"
        factor: 2
    on_failure: []
