# Skill Repository Security Audit workflow definitions
# Schedules nightly security audits for configured skill repositories

version: 1

jobs:
  skill_repo_audit:
    description: "Nightly security audit of skill repositories"
    schedule: "30 2 * * *"
    command: "scripts/audit_skill_repos.sh"
    retry:
      max_attempts: 3
      backoff:
        initial_delay: "5m"
        factor: 2
    on_failure:
      - message:
          channel: telegram
          target: "+14123348429"
          message: "Job skill_repo_audit failed after {{attempts}} attempts."
