#!/usr/bin/env python3
"""Read-only ACPX pilot readiness report."""

from __future__ import annotations

import argparse
import json
import shlex
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]


@dataclass
class CommandResult:
    command: str
    ok: bool
    exit_code: int | None
    stdout: str
    stderr: str
    note: str = ""


def _run(argv: list[str], timeout: int = 30) -> CommandResult:
    try:
        proc = subprocess.run(
            argv,
            cwd=ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=timeout,
            check=False,
        )
        return CommandResult(
            command=" ".join(shlex.quote(part) for part in argv),
            ok=proc.returncode == 0,
            exit_code=proc.returncode,
            stdout=(proc.stdout or "").strip(),
            stderr=(proc.stderr or "").strip(),
        )
    except FileNotFoundError:
        return CommandResult(" ".join(argv), False, None, "", f"command not found: {argv[0]}", "missing-command")


def _safe_json(text: str) -> Any | None:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return None


def build_report() -> dict[str, Any]:
    plugins_result = _run(["openclaw", "plugins", "list", "--json"], timeout=60)
    config_result = _run(["openclaw", "config", "get", "plugins", "--json"], timeout=60)
    mcporter_result = _run(["mcporter", "list", "--json"], timeout=30)
    plugins = _safe_json(plugins_result.stdout) if plugins_result.ok else {}
    config = _safe_json(config_result.stdout) if config_result.ok else {}
    acpx_plugin = {}
    if isinstance(plugins, dict):
        for item in plugins.get("plugins", []):
            if isinstance(item, dict) and item.get("id") == "acpx":
                acpx_plugin = item
                break
    acpx_config = {}
    allowlist = []
    if isinstance(config, dict):
        entries = config.get("entries", {})
        if isinstance(entries, dict):
            acpx_config = entries.get("acpx", {}) or {}
        raw_allowlist = config.get("allow", [])
        if isinstance(raw_allowlist, list):
            allowlist = [item for item in raw_allowlist if isinstance(item, str)]

    return {
        "repo_root": str(ROOT),
        "owner": "ATLAS",
        "plugin_status": {
            "status": acpx_plugin.get("status", "unknown"),
            "activation_reason": acpx_plugin.get("activationReason", "unknown"),
            "origin": acpx_plugin.get("origin", "unknown"),
        },
        "live_policy": {
            "allowlisted": "acpx" in allowlist,
            "enabled": bool(acpx_config.get("enabled")),
            "cwd": (acpx_config.get("config") or {}).get("cwd"),
            "permission_mode": (acpx_config.get("config") or {}).get("permissionMode"),
            "non_interactive_permissions": (acpx_config.get("config") or {}).get(
                "nonInteractivePermissions"
            ),
            "plugin_tools_mcp_bridge": (acpx_config.get("config") or {}).get("pluginToolsMcpBridge"),
        },
        "local_mcp_surface": _safe_json(mcporter_result.stdout) if mcporter_result.ok else None,
        "validation_steps": [
            "scope ACPX to bounded specialist execution only",
            "keep Task Packets as the durable async contract",
            "prove value over current sessions_spawn plus Task Packet flow",
            "avoid user-facing ingress changes",
            "keep permissionMode=approve-reads and nonInteractivePermissions=fail",
            "keep pluginToolsMcpBridge disabled until separately approved",
        ],
        "stop_gates": [
            "treating ACPX as the default durable orchestration model",
            "bypassing ORION-only ingress",
            "enabling plugin-tools bridging without bounded validation",
            "broadening ACPX to write-capable or unattended execution",
        ],
        "commands": [asdict(plugins_result), asdict(config_result), asdict(mcporter_result)],
    }


def _render_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# ACPX Pilot Check",
        "",
        "Generated by `python3 scripts/acpx_pilot_check.py`.",
        "",
        "## Status",
        "",
        f"- Owner: `{report['owner']}`",
        f"- Plugin status: `{report['plugin_status']['status']}`",
        f"- Activation reason: `{report['plugin_status']['activation_reason']}`",
        f"- Allowlisted: `{report['live_policy']['allowlisted']}`",
        f"- Enabled in config: `{report['live_policy']['enabled']}`",
        f"- Permission mode: `{report['live_policy']['permission_mode']}`",
        f"- Non-interactive permissions: `{report['live_policy']['non_interactive_permissions']}`",
        f"- MCP bridge enabled: `{report['live_policy']['plugin_tools_mcp_bridge']}`",
        "",
        "## Validation Steps",
        "",
    ]
    for step in report["validation_steps"]:
        lines.append(f"- {step}")
    lines.extend(["", "## Stop Gates", ""])
    for gate in report["stop_gates"]:
        lines.append(f"- {gate}")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build an ACPX pilot readiness report.")
    parser.add_argument("--output-json", help="Write JSON report to this path.")
    parser.add_argument("--output-md", help="Write markdown report to this path.")
    args = parser.parse_args()
    report = build_report()
    payload = json.dumps(report, indent=2) + "\n"
    markdown = _render_markdown(report) + "\n"
    if args.output_json:
        out = Path(args.output_json)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(payload, encoding="utf-8")
    if args.output_md:
        out = Path(args.output_md)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(markdown, encoding="utf-8")
    print(payload)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
