#!/usr/bin/env python3
"""Read-only ACPX runtime smoke test for the bounded live path."""

from __future__ import annotations

import argparse
import json
import shlex
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]


@dataclass
class CommandResult:
    command: str
    ok: bool
    exit_code: int | None
    stdout: str
    stderr: str
    note: str = ""


def _run(argv: list[str], timeout: int = 30) -> CommandResult:
    try:
        proc = subprocess.run(
            argv,
            cwd=ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=timeout,
            check=False,
        )
        return CommandResult(
            command=" ".join(shlex.quote(part) for part in argv),
            ok=proc.returncode == 0,
            exit_code=proc.returncode,
            stdout=(proc.stdout or "").strip(),
            stderr=(proc.stderr or "").strip(),
        )
    except FileNotFoundError:
        return CommandResult(" ".join(argv), False, None, "", f"command not found: {argv[0]}", "missing-command")


def _safe_json(text: str) -> Any | None:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return None


def _find_plugin(plugins_payload: dict[str, Any], plugin_id: str) -> dict[str, Any]:
    for item in plugins_payload.get("plugins", []):
        if isinstance(item, dict) and item.get("id") == plugin_id:
            return item
    return {}


def build_report() -> dict[str, Any]:
    validate_result = _run(["openclaw", "config", "validate", "--json"], timeout=60)
    config_result = _run(["openclaw", "config", "get", "plugins", "--json"], timeout=60)
    plugins_result = _run(["openclaw", "plugins", "list", "--json"], timeout=60)

    config = _safe_json(config_result.stdout) if config_result.ok else {}
    plugins = _safe_json(plugins_result.stdout) if plugins_result.ok else {}
    validate = _safe_json(validate_result.stdout) if validate_result.ok else {}

    allowlist = config.get("allow", []) if isinstance(config, dict) else []
    entries = config.get("entries", {}) if isinstance(config, dict) else {}
    acpx_config = entries.get("acpx", {}) if isinstance(entries, dict) else {}
    acpx_plugin = _find_plugin(plugins if isinstance(plugins, dict) else {}, "acpx")
    bounded_config = acpx_config.get("config", {}) if isinstance(acpx_config, dict) else {}

    checks = {
        "config_valid": bool(validate.get("valid")) if isinstance(validate, dict) else False,
        "allowlisted": "acpx" in allowlist if isinstance(allowlist, list) else False,
        "enabled_in_config": bool(acpx_config.get("enabled")) if isinstance(acpx_config, dict) else False,
        "plugin_loaded": acpx_plugin.get("status") == "loaded",
        "cwd_matches_repo": bounded_config.get("cwd") == str(ROOT),
        "permission_mode_is_approve_reads": bounded_config.get("permissionMode") == "approve-reads",
        "non_interactive_permissions_fail": bounded_config.get("nonInteractivePermissions") == "fail",
        "plugin_tools_bridge_disabled": bounded_config.get("pluginToolsMcpBridge") is False,
    }
    passed = all(checks.values())

    return {
        "repo_root": str(ROOT),
        "owner": "ATLAS",
        "passed": passed,
        "checks": checks,
        "plugin_status": {
            "status": acpx_plugin.get("status", "unknown"),
            "activation_reason": acpx_plugin.get("activationReason", "unknown"),
            "origin": acpx_plugin.get("origin", "unknown"),
        },
        "bounded_config": bounded_config,
        "commands": [asdict(validate_result), asdict(config_result), asdict(plugins_result)],
    }


def _render_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# ACPX Runtime Smoke",
        "",
        "Generated by `python3 scripts/acpx_runtime_smoke.py`.",
        "",
        "## Result",
        "",
        f"- Passed: `{report['passed']}`",
        f"- Plugin status: `{report['plugin_status']['status']}`",
        f"- Activation reason: `{report['plugin_status']['activation_reason']}`",
        "",
        "## Checks",
        "",
    ]
    for name, value in report["checks"].items():
        lines.append(f"- {name}: `{value}`")
    lines.extend(["", "## Bounded Config", ""])
    for key in ("cwd", "permissionMode", "nonInteractivePermissions", "pluginToolsMcpBridge"):
        lines.append(f"- {key}: `{report['bounded_config'].get(key)}`")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Run a read-only ACPX runtime smoke test.")
    parser.add_argument("--output-json", help="Write JSON report to this path.")
    parser.add_argument("--output-md", help="Write markdown report to this path.")
    args = parser.parse_args()
    report = build_report()
    payload = json.dumps(report, indent=2) + "\n"
    markdown = _render_markdown(report) + "\n"
    if args.output_json:
        out = Path(args.output_json)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(payload, encoding="utf-8")
    if args.output_md:
        out = Path(args.output_md)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(markdown, encoding="utf-8")
    print(payload)
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
