#!/usr/bin/env python3
"""Non-destructive ClawHub skill refresh workflow report."""

from __future__ import annotations

import argparse
import json
import shlex
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_QUERIES = ["reminders", "notes", "github", "firecrawl"]


@dataclass
class CommandResult:
    command: str
    ok: bool
    exit_code: int | None
    stdout: str
    stderr: str
    note: str = ""


def _run(argv: list[str], timeout: int = 30) -> CommandResult:
    try:
        proc = subprocess.run(
            argv,
            cwd=ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=timeout,
            check=False,
        )
        return CommandResult(
            command=" ".join(shlex.quote(part) for part in argv),
            ok=proc.returncode == 0,
            exit_code=proc.returncode,
            stdout=(proc.stdout or "").strip(),
            stderr=(proc.stderr or "").strip(),
        )
    except FileNotFoundError:
        return CommandResult(
            command=" ".join(shlex.quote(part) for part in argv),
            ok=False,
            exit_code=None,
            stdout="",
            stderr=f"command not found: {argv[0]}",
            note="missing-command",
        )
    except subprocess.TimeoutExpired as exc:
        return CommandResult(
            command=" ".join(shlex.quote(part) for part in argv),
            ok=False,
            exit_code=None,
            stdout=(exc.stdout or "").strip(),
            stderr=(exc.stderr or "").strip(),
            note="timeout",
        )


def _safe_json(text: str) -> Any | None:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return None


def _load_lock() -> dict[str, Any]:
    lock_path = ROOT / ".clawhub" / "lock.json"
    if not lock_path.exists():
        return {"version": 1, "skills": {}}
    return json.loads(lock_path.read_text(encoding="utf-8"))


def _summarize_search_output(text: str, limit: int = 5) -> list[str]:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    return lines[:limit]


def build_report(queries: list[str] | None = None) -> dict[str, Any]:
    chosen_queries = queries or list(DEFAULT_QUERIES)
    lock = _load_lock()
    tracked_skills = sorted((lock.get("skills") or {}).keys())

    commands: list[CommandResult] = []
    list_result = _run(["openclaw", "skills", "list"], timeout=8)
    commands.append(list_result)

    search_rows: list[dict[str, Any]] = []
    for query in chosen_queries:
        result = _run(["openclaw", "skills", "search", query], timeout=8)
        commands.append(result)
        search_rows.append(
            {
                "query": query,
                "ok": result.ok,
                "results_preview": _summarize_search_output(result.stdout),
            }
        )

    return {
        "repo_root": str(ROOT),
        "tracked_skills": tracked_skills,
        "queries": chosen_queries,
        "search_rows": search_rows,
        "tracked_skill_info": [],
        "recommended_actions": {
            "review_command": "python3 scripts/clawhub_skill_refresh.py --output-json tmp/clawhub_skill_refresh_latest.json --output-md tmp/clawhub_skill_refresh_latest.md",
            "inspect_command_example": "openclaw skills info <slug> --json",
            "update_command": "openclaw skills update --all",
            "policy": "review artifact first; update only after curator review",
        },
        "commands": [asdict(item) for item in commands],
    }


def _render_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# ClawHub Skill Refresh",
        "",
        "Generated by `python3 scripts/clawhub_skill_refresh.py`.",
        "",
        "## Tracked Skills",
        "",
        f"- Count: `{len(report['tracked_skills'])}`",
        f"- Slugs: `{', '.join(report['tracked_skills'])}`",
        "",
        "## Query Review",
        "",
        "| Query | Status | Preview |",
        "| --- | --- | --- |",
    ]
    for row in report["search_rows"]:
        preview = "; ".join(row["results_preview"]) or "no preview"
        lines.append(f"| `{row['query']}` | `{'ok' if row['ok'] else 'error'}` | {preview} |")

    lines.extend(
        [
            "",
            "## Workflow",
            "",
            f"- Review command: `{report['recommended_actions']['review_command']}`",
            f"- Inspect command example: `{report['recommended_actions']['inspect_command_example']}`",
            f"- Update command: `{report['recommended_actions']['update_command']}`",
            f"- Policy: {report['recommended_actions']['policy']}",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a non-destructive ClawHub refresh report.")
    parser.add_argument("--query", action="append", default=[], help="Add a search query.")
    parser.add_argument("--output-json", help="Write JSON report to this path.")
    parser.add_argument("--output-md", help="Write markdown report to this path.")
    args = parser.parse_args()

    queries = args.query or None
    report = build_report(queries=queries)
    payload = json.dumps(report, indent=2) + "\n"
    markdown = _render_markdown(report) + "\n"

    if args.output_json:
        out = Path(args.output_json)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(payload, encoding="utf-8")
    if args.output_md:
        out = Path(args.output_md)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(markdown, encoding="utf-8")

    print(payload)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
