#!/usr/bin/env python3
"""Read-only Firecrawl pilot readiness report for WIRE."""

from __future__ import annotations

import argparse
import json
import shlex
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]


@dataclass
class CommandResult:
    command: str
    ok: bool
    exit_code: int | None
    stdout: str
    stderr: str
    note: str = ""


def _run(argv: list[str], timeout: int = 30) -> CommandResult:
    try:
        proc = subprocess.run(
            argv,
            cwd=ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=timeout,
            check=False,
        )
        return CommandResult(
            command=" ".join(shlex.quote(part) for part in argv),
            ok=proc.returncode == 0,
            exit_code=proc.returncode,
            stdout=(proc.stdout or "").strip(),
            stderr=(proc.stderr or "").strip(),
        )
    except FileNotFoundError:
        return CommandResult(" ".join(argv), False, None, "", f"command not found: {argv[0]}", "missing-command")


def _safe_json(text: str) -> Any | None:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return None


def build_report() -> dict[str, Any]:
    plugins_result = _run(["openclaw", "plugins", "list", "--json"], timeout=60)
    search_result = _run(["openclaw", "skills", "search", "firecrawl"], timeout=60)
    plugins = _safe_json(plugins_result.stdout) if plugins_result.ok else {}
    firecrawl_plugin = {}
    if isinstance(plugins, dict):
        for item in plugins.get("plugins", []):
            if isinstance(item, dict) and item.get("id") == "firecrawl":
                firecrawl_plugin = item
                break

    return {
        "repo_root": str(ROOT),
        "owner": "WIRE",
        "plugin_status": {
            "status": firecrawl_plugin.get("status", "unknown"),
            "activation_reason": firecrawl_plugin.get("activationReason", "unknown"),
            "origin": firecrawl_plugin.get("origin", "unknown"),
        },
        "skill_search_preview": [line.strip() for line in search_result.stdout.splitlines() if line.strip()][:8],
        "validation_steps": [
            "keep WIRE as the evidence-owning agent",
            "compare one Firecrawl-assisted retrieval against current WIRE workflow",
            "require links and source-aware summaries in every result",
            "do not enable plugin/runtime changes in this tranche",
        ],
        "stop_gates": [
            "plugin enablement without explicit follow-on implementation pass",
            "loss of link-backed retrieval outputs",
            "browser/plugin sprawl that bypasses current evidence discipline",
        ],
        "commands": [asdict(plugins_result), asdict(search_result)],
    }


def _render_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Firecrawl WIRE Pilot",
        "",
        "Generated by `python3 scripts/firecrawl_wire_pilot.py`.",
        "",
        "## Status",
        "",
        f"- Owner: `{report['owner']}`",
        f"- Plugin status: `{report['plugin_status']['status']}`",
        f"- Activation reason: `{report['plugin_status']['activation_reason']}`",
        "",
        "## Search Preview",
        "",
    ]
    for line in report["skill_search_preview"]:
        lines.append(f"- {line}")
    lines.extend(["", "## Validation Steps", ""])
    for step in report["validation_steps"]:
        lines.append(f"- {step}")
    lines.extend(["", "## Stop Gates", ""])
    for gate in report["stop_gates"]:
        lines.append(f"- {gate}")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a Firecrawl pilot readiness report.")
    parser.add_argument("--output-json", help="Write JSON report to this path.")
    parser.add_argument("--output-md", help="Write markdown report to this path.")
    args = parser.parse_args()
    report = build_report()
    payload = json.dumps(report, indent=2) + "\n"
    markdown = _render_markdown(report) + "\n"
    if args.output_json:
        out = Path(args.output_json)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(payload, encoding="utf-8")
    if args.output_md:
        out = Path(args.output_md)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(markdown, encoding="utf-8")
    print(payload)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
