#!/usr/bin/env python3
"""Read-only GitHub structured workflow pilot report."""

from __future__ import annotations

import argparse
import json
import shlex
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]


@dataclass
class CommandResult:
    command: str
    ok: bool
    exit_code: int | None
    stdout: str
    stderr: str
    note: str = ""


def _run(argv: list[str], timeout: int = 30) -> CommandResult:
    try:
        proc = subprocess.run(
            argv,
            cwd=ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=timeout,
            check=False,
        )
        return CommandResult(
            command=" ".join(shlex.quote(part) for part in argv),
            ok=proc.returncode == 0,
            exit_code=proc.returncode,
            stdout=(proc.stdout or "").strip(),
            stderr=(proc.stderr or "").strip(),
        )
    except FileNotFoundError:
        return CommandResult(" ".join(argv), False, None, "", f"command not found: {argv[0]}", "missing-command")


def _safe_json(text: str) -> Any | None:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return None


def build_report() -> dict[str, Any]:
    gh_version = _run(["gh", "--version"], timeout=10)
    gh_repo = _run(["gh", "repo", "view", "--json", "nameWithOwner,defaultBranchRef"], timeout=20)
    gh_auth = _run(["gh", "auth", "status"], timeout=20)
    return {
        "repo_root": str(ROOT),
        "owner": "ORION/ATLAS",
        "gh_version": gh_version.stdout.splitlines()[0] if gh_version.stdout else "",
        "repo_view": _safe_json(gh_repo.stdout) if gh_repo.ok else None,
        "auth_ok": gh_auth.ok,
        "validation_steps": [
            "keep gh as the stable fallback",
            "use structured reads first for repo, PR, checks, and issue context",
            "avoid replacing existing working gh flows without clear gain",
            "preserve explicit proof and operator-readable outputs",
        ],
        "stop_gates": [
            "opaque automation that hides repo/PR/CI evidence",
            "extra auth sprawl without clear payoff",
            "replacing gh for commands it already handles cleanly",
        ],
        "commands": [asdict(gh_version), asdict(gh_repo), asdict(gh_auth)],
    }


def _render_markdown(report: dict[str, Any]) -> str:
    repo_view = report["repo_view"] or {}
    lines = [
        "# GitHub Structured Workflow Pilot",
        "",
        "Generated by `python3 scripts/github_structured_workflow_pilot.py`.",
        "",
        "## Status",
        "",
        f"- Owner: `{report['owner']}`",
        f"- gh version: `{report['gh_version']}`",
        f"- Auth OK: `{report['auth_ok']}`",
        f"- Repo: `{repo_view.get('nameWithOwner', 'unknown')}`",
        "",
        "## Validation Steps",
        "",
    ]
    for step in report["validation_steps"]:
        lines.append(f"- {step}")
    lines.extend(["", "## Stop Gates", ""])
    for gate in report["stop_gates"]:
        lines.append(f"- {gate}")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a GitHub structured workflow pilot report.")
    parser.add_argument("--output-json", help="Write JSON report to this path.")
    parser.add_argument("--output-md", help="Write markdown report to this path.")
    args = parser.parse_args()
    report = build_report()
    payload = json.dumps(report, indent=2) + "\n"
    markdown = _render_markdown(report) + "\n"
    if args.output_json:
        out = Path(args.output_json)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(payload, encoding="utf-8")
    if args.output_md:
        out = Path(args.output_md)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(markdown, encoding="utf-8")
    print(payload)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
