#!/usr/bin/env python3
"""
Weekly online skill discovery scan for OpenClaw sources.

Read-only pipeline:
- Fetch official docs sitemap and official OpenClaw GitHub releases feed.
- Infer candidate capabilities via URL/title heuristics.
- Score candidates against the intake rubric dimensions.
- Write timestamped artifacts to eval/history.
- Optionally upsert an autogenerated section in the weekly shortlist doc.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import urllib.error
import urllib.request
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo


OFFICIAL_DOCS_HOST = "docs.openclaw.ai"
OFFICIAL_GITHUB_HOST = "github.com"
DEFAULT_DOCS_SITEMAP = "https://docs.openclaw.ai/sitemap.xml"
DEFAULT_RELEASES_ATOM = "https://github.com/openclaw/openclaw/releases.atom"
GENERATED_SECTION = "## Automated Discovery (Generated)"
LOCALE_PREFIX_RE = re.compile(r"^[a-z]{2}(?:-[A-Z]{2})?/")

WEIGHTS = {
    "trustworthiness": 20,
    "maintenance": 15,
    "capability_fit": 20,
    "risk": 15,
    "observability": 15,
    "rollback": 15,
}


@dataclass(frozen=True)
class CapabilityProfile:
    name: str
    capability: str
    risk_note: str
    expected_roi: str
    test_plan: str
    base_fit: float
    risk_score: float
    observability_score: float
    rollback_score: float


PROFILE_AUTOMATION = CapabilityProfile(
    name="automation",
    capability="Automation trigger orchestration",
    risk_note="Trigger misconfiguration can create duplicate or noisy executions.",
    expected_roi="Lower polling overhead and faster event-to-action latency.",
    test_plan="Stage one trigger in sandbox, replay sample events, compare latency and errors.",
    base_fit=4.4,
    risk_score=3.0,
    observability_score=4.0,
    rollback_score=4.0,
)

PROFILE_CHANNELS = CapabilityProfile(
    name="channels",
    capability="Channel delivery integration",
    risk_note="Routing mistakes can send messages to wrong recipients or duplicate sends.",
    expected_roi="Expand delivery coverage with less custom channel maintenance.",
    test_plan="Send canary messages to non-prod channels, verify mapping, dedupe, and audit logs.",
    base_fit=4.0,
    risk_score=2.8,
    observability_score=3.6,
    rollback_score=3.5,
)

PROFILE_SECURITY = CapabilityProfile(
    name="security",
    capability="Auth and access control hardening",
    risk_note="Scope mistakes can over-privilege agents or break critical automation.",
    expected_roi="Reduce security incidents and auth-related operational failures.",
    test_plan="Run least-privilege allow/deny smoke tests and verify credential rollback path.",
    base_fit=3.5,
    risk_score=2.6,
    observability_score=3.6,
    rollback_score=3.6,
)

PROFILE_OBSERVABILITY = CapabilityProfile(
    name="observability",
    capability="Runtime observability and diagnostics",
    risk_note="Low blast radius; main risk is incomplete signal coverage.",
    expected_roi="Faster triage and clearer promotion/rollback gating evidence.",
    test_plan="Inject controlled failure in staging and confirm logs, metrics, and alerts capture it.",
    base_fit=4.1,
    risk_score=4.1,
    observability_score=5.0,
    rollback_score=4.4,
)

PROFILE_WORKFLOW = CapabilityProfile(
    name="workflow",
    capability="Workflow quality and output structure",
    risk_note="Higher process complexity can increase runtime cost if over-applied.",
    expected_roi="Improve output consistency and reduce rerun/edit loops.",
    test_plan="A/B test representative tasks for quality score, revision count, and turnaround.",
    base_fit=4.0,
    risk_score=4.0,
    observability_score=3.2,
    rollback_score=4.2,
)

PROFILE_RELEASE = CapabilityProfile(
    name="release",
    capability="Core runtime upgrade candidate",
    risk_note="Release changes can introduce regressions without staged validation.",
    expected_roi="Adopt upstream fixes and capabilities with lower long-term drift.",
    test_plan="Pin release in staging, run regression suite, compare reliability metrics, confirm rollback.",
    base_fit=4.4,
    risk_score=3.0,
    observability_score=4.0,
    rollback_score=3.0,
)

PROFILE_GENERAL = CapabilityProfile(
    name="general",
    capability="Platform capability discovery",
    risk_note="Scope and integration assumptions may be incomplete until validated.",
    expected_roi="Discover incremental improvements for agent productivity and reliability.",
    test_plan="Create a minimal staged trial with explicit success and rollback criteria.",
    base_fit=3.2,
    risk_score=3.5,
    observability_score=3.3,
    rollback_score=3.8,
)


def _fetch_bytes(url: str, timeout: int = 25) -> bytes:
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": "ORION-skill-discovery/1.0",
            "Accept": "application/xml,text/xml,application/atom+xml,*/*",
        },
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return resp.read()


def _clamp(value: float, lo: float = 0.0, hi: float = 5.0) -> float:
    return max(lo, min(hi, value))


def _clean(text: str) -> str:
    return " ".join((text or "").strip().split())


def _slug_to_title(slug: str) -> str:
    slug = slug.strip().strip("/")
    if not slug:
        return "OpenClaw Docs"
    last = slug.split("/")[-1]
    return " ".join(part.capitalize() for part in last.replace("-", " ").split())


def _host_from_url(url: str) -> str:
    # Avoid importing urllib.parse for this tiny check.
    m = re.match(r"^https?://([^/]+)", url)
    return m.group(1).lower() if m else ""


def _path_from_url(url: str) -> str:
    m = re.match(r"^https?://[^/]+(/.*)?$", url)
    path = m.group(1) if m else ""
    if not path:
        return "/"
    return path


def _days_since(timestamp: dt.datetime, now_utc: dt.datetime) -> int:
    delta = now_utc - timestamp.astimezone(dt.timezone.utc)
    return max(0, int(delta.total_seconds() // 86400))


def _parse_iso_datetime(value: str) -> dt.datetime | None:
    text = (value or "").strip()
    if not text:
        return None
    try:
        return dt.datetime.fromisoformat(text.replace("Z", "+00:00"))
    except ValueError:
        return None


def _priority_bonus(text: str) -> float:
    t = text.lower()
    score = 0.0
    for kw in ("automation", "cron", "gmail", "pubsub", "webhook", "hook", "poll"):
        if kw in t:
            score += 1.2
    for kw in ("telegram", "discord", "routing", "channel", "signal", "slack"):
        if kw in t:
            score += 0.8
    for kw in ("prose", "workflow", "prompt", "plan"):
        if kw in t:
            score += 0.9
    for kw in ("reliability", "monitor", "canary", "health", "troubleshooting", "auth"):
        if kw in t:
            score += 1.0
    return score


def _profile_for_item(source: str, url: str, title: str) -> CapabilityProfile:
    text = f"{url} {title}".lower()

    if source == "release":
        return PROFILE_RELEASE

    if any(k in text for k in ("/automation/", "cron", "webhook", "hook", "poll", "pubsub", "gmail")):
        return PROFILE_AUTOMATION
    if any(k in text for k in ("/channels/", "telegram", "discord", "slack", "signal", "matrix", "msteams", "imessage", "routing")):
        return PROFILE_CHANNELS
    if any(k in text for k in ("auth", "oauth", "permission", "scope", "token", "security")):
        return PROFILE_SECURITY
    if any(k in text for k in ("reliability", "monitor", "metrics", "logs", "troubleshooting", "canary", "health", "incident")):
        return PROFILE_OBSERVABILITY
    if any(k in text for k in ("prose", "workflow", "prompt", "template", "agent")):
        return PROFILE_WORKFLOW
    return PROFILE_GENERAL


def _fit_score(profile: CapabilityProfile, text: str) -> float:
    fit = profile.base_fit
    t = text.lower()
    if any(k in t for k in ("cron", "gmail", "pubsub", "webhook", "routing", "telegram", "prose", "reliability")):
        fit += 0.4
    if any(k in t for k in ("beta", "deprecated", "legacy")):
        fit -= 0.4
    return round(_clamp(fit), 1)


def _trust_score(source: str, url: str, title: str) -> float:
    host = _host_from_url(url)
    title_l = title.lower()

    if source == "docs":
        if host == OFFICIAL_DOCS_HOST:
            return 5.0
        return 2.0

    if source == "release":
        if host != OFFICIAL_GITHUB_HOST:
            return 2.0
        if "openclaw/openclaw/releases/tag/" not in url:
            return 3.0
        if "beta" in title_l or "alpha" in title_l or "rc" in title_l:
            return 4.0
        return 5.0

    return 2.0


def _maintenance_score(last_seen: dt.datetime | None, now_utc: dt.datetime, source: str) -> float:
    if last_seen is None:
        # Docs entries often do not expose publish metadata in sitemap records.
        return 4.0 if source == "docs" else 3.5

    age_days = _days_since(last_seen, now_utc)
    if age_days <= 7:
        return 5.0
    if age_days <= 30:
        return 4.5
    if age_days <= 90:
        return 4.0
    if age_days <= 180:
        return 3.5
    return 3.0


def _risk_score(profile: CapabilityProfile, title: str) -> float:
    score = profile.risk_score
    t = title.lower()
    if "beta" in t or "alpha" in t:
        score -= 0.6
    return round(_clamp(score), 1)


def _observability_score(profile: CapabilityProfile, title: str) -> float:
    score = profile.observability_score
    t = title.lower()
    if any(k in t for k in ("metrics", "logs", "reliability", "troubleshooting")):
        score += 0.3
    return round(_clamp(score), 1)


def _rollback_score(profile: CapabilityProfile, title: str) -> float:
    score = profile.rollback_score
    t = title.lower()
    if "beta" in t:
        score -= 0.4
    return round(_clamp(score), 1)


def _weighted_intake(scores: dict[str, float]) -> float:
    total = 0.0
    for dim, weight in WEIGHTS.items():
        total += (_clamp(scores.get(dim, 0.0)) / 5.0) * float(weight)
    return round(total, 1)


def _status_from_scores(intake: float, dimensions: dict[str, float], hard_reject: bool) -> str:
    if hard_reject:
        return "rejected"
    min_dimension = min(dimensions.values()) if dimensions else 0.0
    if intake >= 78.0 and min_dimension >= 3.0:
        return "intake-ready"
    if intake >= 70.0:
        return "researching"
    return "hold"


def _docs_candidates(sitemap_url: str, now_utc: dt.datetime) -> list[dict[str, Any]]:
    xml_bytes = _fetch_bytes(sitemap_url)
    root = ET.fromstring(xml_bytes)
    ns = {"sm": "http://www.sitemaps.org/schemas/sitemap/0.9"}

    out: list[dict[str, Any]] = []
    seen_urls: set[str] = set()
    for node in root.findall("sm:url", ns):
        loc = _clean(node.findtext("sm:loc", default="", namespaces=ns))
        if not loc or loc in seen_urls:
            continue
        seen_urls.add(loc)

        host = _host_from_url(loc)
        if host != OFFICIAL_DOCS_HOST:
            continue

        path = _path_from_url(loc).strip("/")
        if not path:
            continue
        # Avoid duplicate locale variants for ranking (for example zh-CN/prose).
        if LOCALE_PREFIX_RE.match(path):
            continue
        if path in {"channels", "automation", "docs", "reference"}:
            continue

        title = _slug_to_title(path)
        profile = _profile_for_item("docs", loc, title)
        text = f"{path} {title}"
        trust = _trust_score("docs", loc, title)
        fit = _fit_score(profile, text)

        lastmod = _parse_iso_datetime(_clean(node.findtext("sm:lastmod", default="", namespaces=ns)))
        dims = {
            "trustworthiness": trust,
            "maintenance": _maintenance_score(lastmod, now_utc, "docs"),
            "capability_fit": fit,
            "risk": _risk_score(profile, title),
            "observability": _observability_score(profile, title),
            "rollback": _rollback_score(profile, title),
        }
        intake = _weighted_intake(dims)
        status = _status_from_scores(intake, dims, hard_reject=False)

        out.append(
            {
                "source_type": "docs",
                "source": "Official OpenClaw docs sitemap",
                "source_feed": sitemap_url,
                "title": title,
                "url": loc,
                "path": path,
                "last_seen": lastmod.isoformat() if lastmod else None,
                "capability": profile.capability,
                "capability_category": profile.name,
                "risk": profile.risk_note,
                "expected_roi": profile.expected_roi,
                "test_plan": profile.test_plan,
                "trust_score": trust,
                "fit_score": fit,
                "dimension_scores": dims,
                "intake_score": intake,
                "status": status,
                "priority_hint": round(_priority_bonus(path) + intake / 20.0, 2),
            }
        )

    return out


def _release_candidates(atom_url: str, now_utc: dt.datetime) -> list[dict[str, Any]]:
    xml_bytes = _fetch_bytes(atom_url)
    root = ET.fromstring(xml_bytes)
    ns = {"a": "http://www.w3.org/2005/Atom"}

    out: list[dict[str, Any]] = []
    for node in root.findall("a:entry", ns):
        title = _clean(node.findtext("a:title", default="", namespaces=ns))
        if not title:
            continue

        release_url = ""
        for link in node.findall("a:link", ns):
            if link.attrib.get("rel") == "alternate":
                release_url = _clean(link.attrib.get("href", ""))
                break
        if not release_url:
            continue
        if _host_from_url(release_url) != OFFICIAL_GITHUB_HOST:
            continue
        if "openclaw/openclaw/releases/tag/" not in release_url:
            continue

        updated = _parse_iso_datetime(_clean(node.findtext("a:updated", default="", namespaces=ns)))

        profile = _profile_for_item("release", release_url, title)
        trust = _trust_score("release", release_url, title)
        fit = _fit_score(profile, title)
        dims = {
            "trustworthiness": trust,
            "maintenance": _maintenance_score(updated, now_utc, "release"),
            "capability_fit": fit,
            "risk": _risk_score(profile, title),
            "observability": _observability_score(profile, title),
            "rollback": _rollback_score(profile, title),
        }

        hard_reject = "beta" in title.lower() and dims["risk"] < 2.5
        intake = _weighted_intake(dims)
        status = _status_from_scores(intake, dims, hard_reject=hard_reject)

        out.append(
            {
                "source_type": "release",
                "source": "Official OpenClaw GitHub releases",
                "source_feed": atom_url,
                "title": title,
                "url": release_url,
                "path": release_url.rsplit("/", 1)[-1],
                "last_seen": updated.isoformat() if updated else None,
                "capability": profile.capability,
                "capability_category": profile.name,
                "risk": profile.risk_note,
                "expected_roi": profile.expected_roi,
                "test_plan": profile.test_plan,
                "trust_score": trust,
                "fit_score": fit,
                "dimension_scores": dims,
                "intake_score": intake,
                "status": status,
                "priority_hint": round(_priority_bonus(title) + intake / 20.0, 2),
            }
        )

    return out


def _candidate_sort_key(item: dict[str, Any]) -> tuple[float, float, float]:
    release_bonus = 0.2 if item.get("source_type") == "release" else 0.0
    return (
        float(item.get("intake_score", 0.0)),
        float(item.get("priority_hint", 0.0)) + release_bonus,
        float(item.get("fit_score", 0.0)),
    )


def _select_ranked(candidates: list[dict[str, Any]], limit: int) -> list[dict[str, Any]]:
    if limit <= 0:
        return []

    ordered = sorted(candidates, key=_candidate_sort_key, reverse=True)

    selected: list[dict[str, Any]] = []
    per_category: dict[str, int] = {}
    max_per_category = 2

    for item in ordered:
        cat = str(item.get("capability_category") or "general")
        if per_category.get(cat, 0) >= max_per_category:
            continue
        selected.append(item)
        per_category[cat] = per_category.get(cat, 0) + 1
        if len(selected) >= limit:
            break

    if len(selected) < limit:
        selected_urls = {i["url"] for i in selected}
        for item in ordered:
            if item["url"] in selected_urls:
                continue
            selected.append(item)
            if len(selected) >= limit:
                break

    for idx, item in enumerate(selected, start=1):
        item["rank"] = idx

    return selected


def _safe_cell(text: str) -> str:
    return _clean(text).replace("|", "/")


def _short_source_label(item: dict[str, Any]) -> str:
    source_type = item.get("source_type")
    if source_type == "docs":
        return f"docs: [{_safe_cell(str(item.get('path', '')))}]({item.get('url')})"
    if source_type == "release":
        return f"release: [{_safe_cell(str(item.get('title', 'release')))}]({item.get('url')})"
    return f"[{_safe_cell(str(item.get('title', 'item')))}]({item.get('url')})"


def _render_generated_table(rows: list[dict[str, Any]]) -> list[str]:
    lines = [
        "| Source | Capability | Risk | Expected ROI | Test Plan | Trust Score | Fit Score | Intake Score | Status |",
        "| --- | --- | --- | --- | --- | ---: | ---: | ---: | --- |",
    ]

    for row in rows:
        lines.append(
            "| "
            + " | ".join(
                [
                    _short_source_label(row),
                    _safe_cell(str(row.get("capability", ""))),
                    _safe_cell(str(row.get("risk", ""))),
                    _safe_cell(str(row.get("expected_roi", ""))),
                    _safe_cell(str(row.get("test_plan", ""))),
                    f"{float(row.get('trust_score', 0.0)):.1f}",
                    f"{float(row.get('fit_score', 0.0)):.1f}",
                    f"{float(row.get('intake_score', 0.0)):.1f}",
                    _safe_cell(str(row.get("status", ""))),
                ]
            )
            + " |"
        )

    if len(rows) == 0:
        lines.append("| (none) | - | - | - | - | 0.0 | 0.0 | 0.0 | hold |")

    return lines


def _upsert_generated_section(shortlist_path: Path, section_lines: list[str], last_updated_et: str | None) -> None:
    lines = shortlist_path.read_text(encoding="utf-8").splitlines() if shortlist_path.exists() else []

    if last_updated_et:
        for i, line in enumerate(lines):
            if line.startswith("Last updated: "):
                lines[i] = f"Last updated: {last_updated_et.split(' ')[0]}"
                break

    if GENERATED_SECTION in lines:
        start = lines.index(GENERATED_SECTION)
        end = len(lines)
        for i in range(start + 1, len(lines)):
            if lines[i].startswith("## "):
                end = i
                break
        replacement = [GENERATED_SECTION, ""] + section_lines
        lines = lines[:start] + replacement + lines[end:]
    else:
        if lines and lines[-1] != "":
            lines.append("")
        lines.extend([GENERATED_SECTION, ""] + section_lines)

    shortlist_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _render_history_md(payload: dict[str, Any]) -> str:
    meta = payload.get("run", {})
    selected = payload.get("selected_candidates", [])

    lines: list[str] = [
        "# Skill Discovery Scan",
        "",
        f"- Generated at ET: `{meta.get('generated_at_et')}`",
        f"- Generated at UTC: `{meta.get('generated_at_utc')}`",
        f"- Limit: `{meta.get('limit')}`",
        f"- Source count: `{meta.get('source_candidate_count')}`",
        f"- Selected count: `{meta.get('selected_count')}`",
        f"- Sources: `{', '.join(meta.get('sources', []))}`",
        "",
        "## Ranked Candidates",
        "",
    ]
    lines.extend(_render_generated_table(selected))
    lines.append("")
    return "\n".join(lines)


def _scan(args: argparse.Namespace) -> dict[str, Any]:
    now_utc = dt.datetime.now(dt.timezone.utc)
    now_et = now_utc.astimezone(ZoneInfo(args.timezone))

    docs_errors: list[str] = []
    release_errors: list[str] = []

    docs = []
    releases = []

    try:
        docs = _docs_candidates(args.docs_sitemap_url, now_utc)
    except (urllib.error.URLError, TimeoutError, ET.ParseError) as exc:
        docs_errors.append(str(exc))

    try:
        releases = _release_candidates(args.releases_atom_url, now_utc)
    except (urllib.error.URLError, TimeoutError, ET.ParseError) as exc:
        release_errors.append(str(exc))

    all_candidates = docs + releases
    selected = _select_ranked(all_candidates, args.limit)

    return {
        "kind": "skills_discovery_scan",
        "run": {
            "generated_at_utc": now_utc.isoformat(),
            "generated_at_et": now_et.strftime("%Y-%m-%d %H:%M"),
            "timezone": args.timezone,
            "limit": args.limit,
            "source_candidate_count": len(all_candidates),
            "selected_count": len(selected),
            "sources": [args.docs_sitemap_url, args.releases_atom_url],
            "errors": {
                "docs": docs_errors,
                "releases": release_errors,
            },
        },
        "selected_candidates": selected,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Run weekly online skill discovery scan.")
    parser.add_argument("--limit", type=int, default=8, help="Max ranked candidates to keep.")
    parser.add_argument("--timezone", default="America/New_York")
    parser.add_argument("--history-dir", default="eval/history")
    parser.add_argument("--docs-sitemap-url", default=DEFAULT_DOCS_SITEMAP)
    parser.add_argument("--releases-atom-url", default=DEFAULT_RELEASES_ATOM)
    parser.add_argument("--shortlist", default="docs/skills/shortlist-2026-03-weekly.md")
    parser.add_argument("--update-shortlist", action="store_true")
    args = parser.parse_args()

    if args.limit < 1:
        raise SystemExit("--limit must be >= 1")

    payload = _scan(args)
    ts = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d-%H%M%S")

    history_dir = Path(args.history_dir)
    history_dir.mkdir(parents=True, exist_ok=True)

    json_path = history_dir / f"skills-discovery-{ts}.json"
    md_path = history_dir / f"skills-discovery-{ts}.md"

    payload["run"]["json_artifact"] = json_path.as_posix()
    payload["run"]["md_artifact"] = md_path.as_posix()

    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    md_path.write_text(_render_history_md(payload), encoding="utf-8")

    if args.update_shortlist:
        shortlist_path = Path(args.shortlist)
        run = payload["run"]
        section_lines = [
            f"- Generated at (ET): `{run.get('generated_at_et')}`",
            f"- Sources: `{', '.join(run.get('sources', []))}`",
            f"- Limit: `{run.get('limit')}`",
            f"- JSON artifact: `{run.get('json_artifact')}`",
            f"- Markdown artifact: `{run.get('md_artifact')}`",
            "",
        ]
        section_lines.extend(_render_generated_table(payload.get("selected_candidates", [])))
        _upsert_generated_section(shortlist_path, section_lines, str(run.get("generated_at_et") or ""))

    print("SKILL_DISCOVERY_SCAN")
    print(f"json: {json_path.resolve()}")
    print(f"md: {md_path.resolve()}")
    print(f"source_candidates: {payload['run']['source_candidate_count']}")
    print(f"selected_candidates: {payload['run']['selected_count']}")
    if args.update_shortlist:
        print(f"shortlist_updated: {Path(args.shortlist).resolve()}")
    else:
        print("shortlist_updated: false")

    docs_errors = payload["run"]["errors"].get("docs") or []
    releases_errors = payload["run"]["errors"].get("releases") or []
    if docs_errors or releases_errors:
        print(f"docs_errors: {len(docs_errors)}")
        print(f"releases_errors: {len(releases_errors)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
